name: pr-comment

on:
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Get Date
        id: get-date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Cache PIP packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ steps.get-date.outputs.date }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: PIP Installer
        uses: BSFishy/pip-action@v1
        with:
          packages: pros-cli

      - name: Install ARM Toolchain
        uses: fiam/arm-none-eabi-gcc@v1
        with:
          release: '10-2020-q4'
  
      - name: Testing PROS Install 
        run: pros --version

      - name: Create Pixel template
        run: pros m template

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: template
          path: 'template.zip'
          retention-days: 89

      - name: Comment PR
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs');
            const zip = fs.readFileSync('template.zip', 'base64');
            const issue_number = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            github.rest.issues.createComment({
              owner: owner,
              repo: repo,
              issue_number: issue_number,
              body: "Here's the template zip file:\n\n```" + zip + "```"
            });