name: pr-comment
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pr_comment:
    runs-on: ubuntu-latest

    permissions: 
      pull-requests: write
    
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const exec = require('@actions/exec');
            const core = require('@actions/core');
            const github = require('@actions/github');
            const fs = require('fs');
            const path = require('path');

            // Run pros m template
            let output = '';
            let error = '';
            const options = {};
            options.listeners = {
              stdout: (data) => {
                output += data.toString();
              },
              stderr: (data) => {
                error += data.toString();
              }
            };
            await exec.exec('pros m template', [], options);
            if (error) {
              core.setFailed(`Failed to run pros m template: ${error}`);
              return;
            }

            // The output file name. Adjust this if the output of 'pros m template' is different.
            const outputFile = 'template.zip';

            // Upload the output file as an artifact
            const artifact = await github.rest.actions.uploadArtifact({
              owner: github.context.repo.owner,
              repo: github.context.repo.repo,
              artifact_name: 'template',
              file: fs.createReadStream(path.join(process.cwd(), outputFile)),
              content_length: fs.statSync(outputFile).size,
              content_type: 'application/zip',
            });

            // Post a comment on the pull request with a link to the artifact
            const comment = `Download the template for this pull request: [${artifact.data.url}](${artifact.data.url})`;
            await github.rest.issues.createComment({
              owner: github.context.repo.owner,
              repo: github.context.repo.repo,
              issue_number: github.context.issue.number,
              body: comment,
            });