name: pr-comment
on:
  workflow_run:
    workflows: ['Build Template']
    types: [completed]
jobs:
  pr_comment:
    # if Build Template was successful and ran on a branch that is currently the head in a pull request
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    permissions: 
      pull-requests: write
    
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const exec = require('@actions/exec');
            const core = require('@actions/core');
            const github = require('@actions/github');
            const fs = require('fs');
            const path = require('path');

            // Run pros m template
            let output = '';
            let error = '';
            const options = {};
            options.listeners = {
              stdout: (data) => {
                output += data.toString();
              },
              stderr: (data) => {
                error += data.toString();
              }
            };
            await exec.exec('pros m template', [], options);
            if (error) {
              core.setFailed(`Failed to run pros m template: ${error}`);
              return;
            }

            // Zip the output
            const zipFile = 'template.zip';
            await exec.exec('zip', ['-r', zipFile, '.']);

            // Upload the zip file as an artifact
            const artifact = await github.rest.actions.uploadArtifact({
              owner: github.context.repo.owner,
              repo: github.context.repo.repo,
              artifact_name: 'template',
              file: fs.createReadStream(path.join(process.cwd(), zipFile)),
              content_length: fs.statSync(zipFile).size,
              content_type: 'application/zip',
            });

            // Post a comment on the pull request with a link to the artifact
            const comment = `Download the template for this pull request: [${artifact.data.url}](${artifact.data.url})`;
            await github.rest.issues.createComment({
              owner: github.context.repo.owner,
              repo: github.context.repo.repo,
              issue_number: github.context.issue.number,
              body: comment,
            });