name: PROS Template
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install ARM Toolchain
        uses: fiam/arm-none-eabi-gcc@v1
        with:
          release: '10-2020-q4'

      - name: PIP Installer
        uses: BSFishy/pip-action@v1
        with:
          packages: pros-cli

      - name: Build PROS Project
        run: make clean quick -j

      - name: Create Pixel template
        run: pros make template

      - name: Get zip file name
        id: get-zip
        run: echo "::set-output name=zip::$(ls *.zip)"

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: template
          path: ${{ steps.get-zip.outputs.zip }}

  comment:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: template

      - name: Comment PR
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs');
            const artifact = fs.readdirSync('.').find(file => file.endsWith('.zip'));
            const url = `https://github.com/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}`;
            const message = `Download the PROS template [here](${url}/artifacts/${artifact})`;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });