name: PROS Template
on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install ARM Toolchain
        uses: fiam/arm-none-eabi-gcc@v1
        with:
          release: '10-2020-q4'

      - name: PIP Installer
        uses: BSFishy/pip-action@v1
        with:
          packages: pros-cli

      - name: Build PROS Project
        run: make clean quick -j

      - name: Create Pixel template
        run: pros make template

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: template
          path: '*.zip'

      - name: Comment PR
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs');
            return github => {
              const issue_number = github.context.issue.number;
              const owner = github.context.repo.owner;
              const repo = github.context.repo.repo;
              const artifacts = fs.readdirSync('.');
              const zipFile = artifacts.find(file => file.endsWith('.zip'));
              if (zipFile) {
                return github.issues.createComment({
                  issue_number: issue_number,
                  owner: owner,
                  repo: repo,
                  body: `Here is the output zip file: ${zipFile}`
                });
              }
            }

      - name: Upload zip file
        uses: actions/upload-artifact@v2
        with:
          name: output-zip
          path: '*.zip'