name: pr-comment

on:
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
  
      - name: PIP Installer
        uses: BSFishy/pip-action@v1
        with:
          packages: pros-cli
  
      - name: Testing PROS Install 
        run: pros --version

      - name: Build PROS Project  
        run: make clean quick -j

      - name: Create Pixel template
        run: pros m template

      - name: Create template folder
        run: mkdir template

      - name: Unzip Template
        uses: montudor/action-zip@v1.0.0
        with:
          args: unzip "template.zip" -d template
  
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: template
          path: 'template/*'
          retention-days: 89

      - name: Comment PR
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs');
            const zip = fs.readFileSync('template/template.zip', 'base64');
            const issue_number = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            github.rest.issues.createComment({
              owner: owner,
              repo: repo,
              issue_number: issue_number,
              body: "Here's the template zip file:\n\n```" + zip + "```"
            });