name: PROS Template
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate unique key
        id: cache-key
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ steps.cache-key.outputs.date }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install ARM Toolchain
        uses: fiam/arm-none-eabi-gcc@v1
        with:
          release: '10-2020-q4'

      - name: PIP Installer
        uses: BSFishy/pip-action@v1
        with:
          packages: pros-cli

      - name: Build PROS Project
        run: make clean quick -j

      - name: Create Pixel template
        run: pros make template

      - name: Get zip file name
        id: get-zip
        run: echo "::set-output name=zip::$(ls *.zip | sed 's/.zip//')"

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.get-zip.outputs.zip }}
          path: ${{ steps.get-zip.outputs.zip }}.zip
    outputs:
      zip: ${{ steps.get-zip.outputs.zip }}